PREFIX owl: <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT ?entity ?property ?value
WHERE {
  VALUES ?property { owl:equivalentClass }
  ?entity owl:equivalentClass ?value .
  FILTER (?entity = ?value)
  FILTER NOT EXISTS { ?entity owl:deprecated true }
  FILTER (!isBlank(?entity))
}
