# Basic ODK workflow

name: CI

# Controls when the action will run.
on:
  push:
    branches:
      - main
      - odk-migration
  pull_request:
    branches:
      - main
      - odk-migration

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ontology_qc:
    runs-on: ubuntu-latest
    container: obolibrary/odkfull:v1.6

    steps:
      - uses: actions/checkout@v4

      - name: Run QC and build release artefacts
        env:
          DEFAULT_BRANCH: main
        run: cd src/ontology && make ROBOT_ENV='ROBOT_JAVA_ARGS=-Xmx6G' prepare_release_fast -B

      - name: Upload release artefacts
        uses: actions/upload-artifact@v4
        with:
          name: pbpko-release
          path: |
            pbpko.owl
            pbpko.obo
            pbpko.json
            pbpko-base.owl
            pbpko-base.obo
            pbpko-base.json
            pbpko-full.owl
            pbpko-full.obo
            pbpko-full.json
            imports/
            mappings/
